### ISSUE TITLE
Doggo's Bug & task list for drill [close once all tasks are checked]

### ISSUE THREAD

**Issue by Shibva** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#150]
- [ ] __Replace the Thomson Machine gun with the proper model__ [not sure if you want to keep the cat joke render you made]
- [ ] Update revolver models to the newer ones
- [ ] Remove the old recipes for the following items (check when all are done)
       

   - [ ]  Power Fist (Claw) [their are 2 recipes, the one that makes it in claw mode is the old and removed one

   - [ ] Old turrets (minus a few exceptions) [this one im not sure on if they were removed or not, but if they were not then the recipes to make them (and template) need to be removed
   - [ ] 
- [ ] Attribute fixes (check when all are done)
     - [ ] Coal Powder (shows code name still instead of proper name
     - [ ] Asbestos (needs to be added to all oredict items of asbestos ( Ingot, powder, block); also is displaying its code name )
     - [ ] New armors (some of the things that are in the full set bonus are being displayed by their attribute code name [Fau, DNT armor, etc]
     - [ ] Explosive/Flammable [needs to be implemented to items like gunpowder, tnt and Semtex]
     - [ ] Hydroreactive [lithium and block need a tag added and to react if items with this tag touch water, even if your in the hand while in water.]
     
- [ ] (TBD) fixing rendering issue when holding the Occult Shotgun, Gluon Gun, and Crucible when "Main Hand" setting in skin customization is set to left (will also not play sounds)
- [ ] Gluon Gun beam rendering for a split second if you deselect it while firing and then going back on it when not holding RMB
- [ ] Event where pushing "Resume" while having a gun in your hand will cause it to fire a round (So far observed with Occult Shotgun and the Super Shotgun; may be the case overall with the other guns
- [ ] Remove/change items (check when done
     - [ ] Remove outdated and old Cyclotron items (recipe's for the tower and the one magnet have been removed yet the item was kept in the game for some reason)
     - [ ] Old ammunitions' regarding the Nuclear Catapult needs to have "(Legacy)" added to them and a recipe option to exchange the old ones for the new one
     
- [ ] (unsure, try thinking about this) Finish up Super shotgun or "polish it up" for usability and plans for it to be fixed up/updated later on. Things that need before its ready:
    - [ ] Custom Model texture
    - [ ] Special FX for using it (Like the Occult shotgun) for the firing animation and the "meathook" [Recommend re-using the Occult shotguns bullet visuals and adjusts them for use with the S-Shotgun as a "Placeholder" till a more suitable one is made (Personally think that doing this might be better than trying to make a new visual from scratch
    
- [ ] [Recommendation] Adjust the Occult shotgun to be able to use any ammo in the 12 gauge ammunition category
- [ ] reload animation and sounds to be replayed depending on reload status if the weapon is switched out during reload [it will not play the effects or sounds of it reloading again]
- [ ] Investigate and fix issue with the Crucible and related weapons "L-Cut" effect doesn't work on all models that are like the case for those in the Ice and fire mod [while the cut model will not show up if you use it on one of the entities like a dragon (for example) yet the gluon gun being able to do its effects of "atomic dismembering" on the same model
- [ ] Fix Crucible's "item select" animation being played again if used to kill any mob (regular attack; __Will Only be able to reproduce when in SURVIVAL MODE ONLY__)
- [ ] Add an Experimental setting (sets to false by default in the config or if possible be a gamerule set to false by default) that when set to true will keep the "entity" that generates the explosion crater from unloading when outside of render distance [add a lag warning to this if it has to be a config option thing] (this is due to the explosion and crater "replaying" or "resuming" if this entity becomes unloaded when outside of player chunkloaded render distance)

- [ ] (unlikely to be fixed but added) Fix issue with layers added by armor system not being able to sync with helmet movement when player animations with Mo' bends is enabled [an update was posted somewhat recently]
- [ ] Make it where you can refuel the Glider without having to take it out of the armor via Modification Table (if possible)
- [ ] [recommendation] have the cape visual (regular Minecraft code) be suppressed (hidden) if your wearing something with the Glider modification on it
- [ ] add recipes to the 3 obtainable capes (they have been without a recipe in this fork for quite some time now

That is all I can think of for now, ill post more in this format if I find anything else; Don't forget to check the boxes out accordingly once one of the issues have been resolved. Might not also be a bad idea to pin this on the issue tracker so you can refer back to it easier

hope this helps drill with keeping track of the issues that I have found 😄 
     
Edit: added a few things I forgot to add to this one

- [ ] Fix Turret ID chip not working properly on old turrets (using them will for some reason have them still attack you even when the chip is set to your id
- [ ] New Turrets not being able to be used with the Turret Controller (yes there is functionality with it to the new turrets in 1.7.10)
- [ ] [unsure] not being able to target all entitles when set todo so (idk how you can reproduce this because this was only seen to be happening with mobs that are from a "closed beta" mod im a beta tester for)
- [ ] All turrets being able to target and fire at the player while in creative and spectator mode

- [ ] Update dead grass texture and infernal coal to the new ones
- [ ] Update the Nether Coal Default generation value to the current one (has been lowered in 1.7.10)

**Comment by Drillgon200** [comment]
I don't want to keep issues with old fixed problems around after they've been dealt with, so I will close this when done. Please open a new issue for new issues.

**Comment by Shibva** [comment]
alright
